// English for every Filipino line in the game, keyed by the Filipino (see i18n.mjs). English names:
// House, Classic, Storm, Race, Weekly, Projects, Versus, Head to Head, Training; coins for barya, floors
// for palapag, mud for putik; the ranks Laborer → Architect; Bayanihan stays (glossed in How to Play).
export const EN = {
  "Kita": "Earnings",
  "Palapag 1 · 0 hanay": "Floor 1 · 0 lines",
  "E · GAMIT": "E · TOOL",
  "Hinto": "Pause",
  "MULTO": "GHOST",
  "Ulit · Retry (R)": "Retry (R)",
  "INSPEKSYON": "INSPECTION",
  "Buuin ang bahay!": "Build the house!",
  "Trabaho na!": "Let's work!",
  "Laro ▸": "Play ▸",
  "Mga Laro": "Modes",
  "Pagsasanay": "Training",
  "Tindahan": "Shop",
  "Koleksyon": "Collection",
  "Tala": "Stats",
  "Ayos": "Settings",
  "Paano": "How to play",
  "Madali": "Easy",
  "Katamtaman": "Medium",
  "Mahirap": "Hard",
  "Bumalik · Back": "Back",
  "Mga Naitayong Bahay": "Houses You Built",
  "Ibahagi · Share image": "Share image",
  "Paalala ni Kapatas": "Kapatas's reminder",
  "\"Sa totoong construction site, laging naka-hard hat, at bawal ang bata doon: delikado! Dito lang tayo maglaro ng hollow blocks.\"": "\"On a real construction site, it's hard hats always, and no kids allowed: it's dangerous! We only play with hollow blocks here.\"",
  "Opo, Kapatas! · Let's go": "Yes, Kapatas! Let's go",
  "Merienda muna · Paused": "Snack break · Paused",
  "Tuloy · Resume": "Resume",
  "Ayos · Settings": "Settings",
  "Ulit · Again": "Again",
  "Susunod na Kontrata": "Next contract",
  "Ibahagi · Share": "Share",
  "Panoorin · Replay": "Watch replay",
  "Bagong ranggo · Rank up": "Rank up",
  "Tuloy · Continue": "Continue",
  "Proyekto · Mga Kontrata": "Projects · Contracts",
  "Simulan · Start": "Start",
  "Simulan na may gamit": "Start with a tool",
  "patalastas": "ad",
  "Sige · OK": "OK",
  "PATALASTAS · TEST AD": "AD · TEST AD",
  "Dito lalabas ang totoong patalastas kapag naikonekta na ang ad network. Tapusin para sa gantimpala.": "The real ad will show here once an ad network is connected. Watch to the end for the reward.",
  "Kunin ang gantimpala": "Claim the reward",
  "Isara · Close": "Close",
  "Mag-login para makasali": "Log in to join",
  "Tala at Medalya": "Stats and medals",
  "Tapos · Done": "Done",
  "Paano Laruin": "How to Play",
  "Galaw:": "Move:",
  "ikot:": "turn:",
  "↑ o X (pabalik: Z),": "↑ or X (back: Z),",
  "dahan:": "soft drop:",
  "bagsak:": "hard drop:",
  "imbak:": "hold:",
  "C o Shift,": "C or Shift,",
  "gamit:": "tool:",
  "hinto:": "pause:",
  "tap para iikot, i-drag para gumalaw, i-flick pababa para ibagsak, pataas para mag-imbak; may mga button din.": "tap to turn, drag to move, flick down to drop, flick up to hold; there are buttons too.",
  "d-pad, ✕ ikot, ○ pabalik, △ imbak, □ gamit.": "d-pad, ✕ turn, ○ turn back, △ hold, □ tool.",
  "apat na hanay nang sabay. Ang T-spin at sunod-sunod na Bayanihan ay may dagdag na kita.": "four lines at once (bayanihan: the whole barangay pitching in). T-spins and back-to-back Bayanihans earn extra.",
  "Gamit (tools):": "Tools:",
  "minsan may kahon ng gamit ang isang piraso. Linisin ang hanay nito (o mag-Bayanihan) para makakuha, hanggang tatlo.": "sometimes a piece carries a toolbox. Clear its line (or score a Bayanihan) to get the tool; you can hold three.",
  "Martilyo: basag ang pinakamataas na bloke sa ilalim ng piraso.": "Hammer: smashes the highest block under the piece.",
  "Semento: tapalan ang mga butas sa ibaba.": "Cement: fills the holes below.",
  "Kreyn: gawing kawayan ang piraso.": "Crane: turns the piece into bamboo.",
  "Pison: patagin ang tumpok.": "Roller: flattens the stack.",
  "Merienda: bagal ang bagsak nang 15 segundo.": "Snack: slower falling for 15 seconds.",
  "Mga mode:": "Modes:",
  "Bahay (walang katapusan), Klasiko (iisang bilis buong laro, walang gamit), Deadline (40 hanay), Bagyo (putik mula sa ilalim), Karera (2 minuto, pinakamataas na kita), Daily (parehong piraso para sa lahat ngayong araw), Proyekto (30 kontrata, 1–3 bituin).": "House (endless), Classic (one speed all game, no tools), Deadline (40 lines), Storm (mud rising from below), Race (2 minutes, highest earnings), Daily (the same pieces for everyone today), Projects (30 contracts, 1–3 stars).",
  "Laban:": "Versus:",
  "ang well mo at ang sa kalaban, magkatabi. Bawat clear ay nagpapadala ng putik (2 hanay = 1, 3 = 2, Bayanihan = 4, T-spin double = 4, may dagdag ang sunod-sunod at combo). Ang paparating na putik (mga sako sa tabi ng well) ay nahaharang ng sarili mong clear. Talunin ang anim sa Liga ng Barangay.": "your well and your rival's, side by side. Every clear sends mud (2 lines = 1, 3 = 2, Bayanihan = 4, T-spin double = 4, more for back-to-back and combos). Incoming mud (the sacks beside the well) is blocked by your own clears. Beat all six in the Barangay League.",
  "Tapatan (2P, desktop):": "Head to Head (2P, desktop):",
  "dalawang tao sa isang keyboard (P1: A D S W, Q E, C; P2: mga arrow, , . /) o may controller. Pinakamahusay sa tatlo; may handicap sa padala at sa simulang taas.": "two people on one keyboard (P1: A D S W, Q E, C; P2: arrows, , . /) or with controllers. Best of three, with handicaps for mud sent and starting height.",
  "Proyekto Kabanata 2:": "Projects Chapter 2:",
  "brownout (flashlight lang), hangin (dumudulas ang piraso), bitak (gumuguho ang bloke), Lunes (walang kawayan), limitadong gamit, at ang City Inspector na nagtatatak ng REJECTED. Linisin ang tatak para may dagdag na oras.": "brownouts (flashlight only), wind (pieces drift), cracks (blocks crumble), Mondays (no bamboo), limited tools, and the City Inspector stamping REJECTED. Clear the stamps for extra time.",
  "Lingguhan:": "Weekly:",
  "bawat linggo, ibang twist (Bagyo, Lindol, Gamit Lang, Mabilis, Retro). Tapusin para sa medalya at token.": "a new twist every week (Storm, Quake, Tools Only, Fast, Retro). Finish it for medals and tokens.",
  "Gamit sa ranggo:": "Rank tools:",
  "Plumada (Kapatas): ipinapakita ang pinakamagandang puwesto ng susunod na tatlong piraso.": "Plumb Line (Foreman rank): shows the best spot for the next three pieces.",
  "Barena (Inhinyero): binubutas ang isang hanay pababa.": "Drill (Engineer rank): bores one column down.",
  "Andamyo (Arkitekto): sasalo ng susunod na putik o isang pagguho.": "Scaffold (Architect rank): catches the next mud or one collapse.",
  "Tindahan:": "Shop:",
  "gastusin ang barya (mula sa bawat laro) at token (mula sa Lingguhan) sa mga skin ng bloke, damit ni Kapatas at tema ng site. Silipin muna bago bilhin. May mga bukas lang sa medalya o ranggo.": "spend coins (from every game) and tokens (from the Weekly) on block skins, outfits for Kapatas and site themes. Preview before you buy. Some only open with a medal or a rank.",
  "Koleksyon:": "Collection:",
  "bawat natapos na bahay sa Bahay (bawat limang palapag) ay may larawan sa aklat. Buksan para sa detalye at ibahagi bilang larawan.": "every house you finish in House mode (every five floors) gets a picture in the book. Open it for the details and share it as an image.",
  "bumalik araw-araw para sa dagdag na XP at barya, hanggang ikapitong araw. May isang palugit na araw kung makaligta ka.": "come back every day for extra XP and coins, up to the seventh day. You get one day of grace if you miss.",
  "mga aralin sa T-spin single, double at triple, 4-wide combo at finesse. Sundan ang gintong anino. Binibilang ng finesse coach ang sayang na pindot.": "lessons in T-spin singles, doubles and triples, the 4-wide combo and finesse. Follow the golden shadow. The finesse coach counts wasted presses.",
  "Replay at multo:": "Replays and ghosts:",
  "naitatala ang bawat laro. Sa Deadline at Karera, hinahabol mo ang multo ng pinakamagandang takbo mo. Panoorin (1×, 2×, 4×) at ibahagi bilang link.": "every game is recorded. In Deadline and Race you race the ghost of your best run. Watch them (1×, 2×, 4×) and share them as links.",
  "Ayos:": "Settings:",
  "bilang ng susunod na piraso, DAS, ARR, bilis ng dahan, 180° na ikot, imbak, at pagpapalit ng mga pindutan sa keyboard at controller.": "how many next pieces to show, DAS, ARR, soft-drop speed, 180° turns, hold, and remapping keyboard and controller buttons.",
  "Ranggo:": "Rank:",
  "bawat laro ay may XP. Mula Peon hanggang Arkitekto, at may bagong istilo ng bahay sa bawat ranggo.": "every game earns XP. From Laborer to Architect, with a new house style at each rank.",
  "Sige! · Got it": "Got it!",
  "Tapatan · 2 Manlalaro": "Head to Head · 2 Players",
  "Dalawang tao, isang computer. Pinakamahusay sa tatlong ronda. Ang handicap: dami ng putik na ipinapadala, at taas ng kalat sa simula.": "Two people, one computer. Best of three rounds. The handicaps: how much mud each side sends, and how high the rubble starts.",
  "Mga pindutan · Keys": "Keys",
  "Laban · Versus": "Versus",
  "Bawat clear, may putik na ipinapadala sa kalaban: 2 hanay = 1, 3 = 2, Bayanihan = 4, T-spin double = 4. Harangin ang paparating sa sarili mong clear.": "Every clear sends mud to your rival: 2 lines = 1, 3 = 2, Bayanihan = 4, T-spin double = 4. Block what's coming with clears of your own.",
  "Mabilisang laban": "Quick match",
  "Liga ng Barangay": "Barangay League",
  "Laban na! · Fight": "Fight!",
  "Pagsasanay · Training": "Training",
  "Mga aralin ni Kapatas. Sundan ang gintong anino. Ang T-spin at combo ang susi sa mga kontratang Diskarte, Sunod-sunod at Tatlong T-spin.": "Kapatas's lessons. Follow the golden shadow. T-spins and combos are the key to the Know-How, Chain Reaction and Three T-spins contracts.",
  "Pasado!": "Passed!",
  "Susunod · Next": "Next",
  "Mga aralin": "Lessons",
  "Mga Replay": "Replays",
  "Ang pinakamagandang takbo mo sa Deadline, Karera at Daily, at ang huling laro. Ibahagi bilang link.": "Your best runs in Deadline, Race and the Daily, and your last game. Share them as links.",
  "Mga Pindutan · Controls": "Controls",
  "Ibalik ang default · Reset": "Reset to default",
  "IMBAK": "HOLD",
  "Isara": "Close",
  "Inihahanda ang site…": "Getting the site ready…",
  "· sa totoong site, laging naka-hard hat ·": "· on a real site, hard hats always ·",
  "AUTO: change speed · bilis": "AUTO: change speed",
  "Itigil ang AUTO · Stop autoplay": "Stop autoplay",
  "Pause · Hinto": "Pause",
  "Patalastas": "Ad",
  "Bahay": "House",
  "BAHAY": "HOUSE",
  "Klasiko": "Classic",
  "Bagyo": "Storm",
  "Karera": "Race",
  "Lingguhan": "Weekly",
  "LINGGUHAN": "WEEKLY",
  "Proyekto": "Projects",
  "Laban": "Versus",
  "LABAN": "VERSUS",
  "Tapatan": "Head to Head",
  "TAPATAN": "HEAD TO HEAD",
  "Peon": "Laborer",
  "Kapatas": "Foreman",
  "Inhinyero": "Engineer",
  "Arkitekto": "Architect",
  "Martilyo": "Hammer",
  "Semento": "Cement",
  "Kreyn": "Crane",
  "Pison": "Roller",
  "Merienda": "Snack",
  "Plumada": "Plumb Line",
  "Barena": "Drill",
  "Andamyo": "Scaffold",
  "Kawayan": "Bamboo",
  "Ladrilyo": "Brick",
  "Yero": "Tin sheet",
  "Baldosa": "Tile",
  "Putik": "Mud",
  "Bahay Kubo": "Nipa Hut",
  "Bahay na Bato": "Stone House",
  "Kabanata 1": "Chapter 1",
  "Kabanata 2 · Sa Lungsod": "Chapter 2 · In the City",
  "Baguhan": "Rookie",
  "Bihasa": "Skilled",
  "Tagasalansan": "Stacker",
  "Lahat": "All-rounder",
  "Bilis": "Speed",
  "Husay": "Skill",
  "Pundasyon": "Foundation",
  "Dalawang Imbak": "Two Holds",
  "Ikalawang Palapag": "Second Floor",
  "Kalat sa Pundasyon": "Rubble on the Foundation",
  "Unang Bayanihan": "First Bayanihan",
  "Diskarte": "Know-How",
  "Sunod-sunod": "Chain Reaction",
  "Ulan sa Gabi": "Night Rain",
  "Lindol!": "Earthquake!",
  "Mabilisang Kontrata": "Rush Job",
  "Gibaan": "Demolition",
  "Walang Imbak": "No Holds",
  "Bagyo at Lindol": "Storm and Quake",
  "Tatlong T-spin": "Three T-spins",
  "Ang Huling Bahay": "The Last House",
  "Habagat": "Monsoon",
  "Bitak": "Cracks",
  "Lunes ng Umaga": "Monday Morning",
  "Gabi ng Habagat": "Monsoon Night",
  "Tipid sa Gamit": "Short on Tools",
  "Bagyo sa Lunes": "Monday Storm",
  "Lumang Pundasyon": "Old Foundation",
  "Bagyong Hangin": "Windstorm",
  "Kandila": "Candlelight",
  "Isang Pison": "One Roller",
  "Lunes at Lindol": "Monday Quake",
  "Bitak sa Bagyo": "Cracks in the Storm",
  "Dilim at Kalat": "Dark and Rubble",
  "Ang Inspektor": "The Inspector",
  "Maglatag muna ng pundasyon: walong hanay.": "Lay the foundation first: eight lines.",
  "Labindalawang hanay, pero dalawang beses lang puwedeng mag-imbak.": "Twelve lines, but you can only hold twice.",
  "Umabot sa ikalawang palapag (10 hanay) sa loob ng 3 minuto.": "Reach the second floor (10 lines) within 3 minutes.",
  "May naiwang kalat sa pundasyon. Linisin lahat ng putik.": "Someone left rubble on the foundation. Clear all the mud.",
  "Apat na hanay nang sabay. Ipunin ang kawayan!": "Four lines at once. Save up the bamboo!",
  "Dalawang T-spin. Iikot ang ladrilyo papasok!": "Two T-spins. Turn the brick in!",
  "Limang sunod-sunod na clear (combo ×4).": "Five clears in a row (combo ×4).",
  "Tumagal nang 90 segundo habang tumataas ang putik.": "Last 90 seconds while the mud rises.",
  "Kumita ng ₱6,000 kahit lumilindol tuwing 30 segundo.": "Earn ₱6,000 while the ground shakes every 30 seconds.",
  "Dalawampung hanay sa 2:30, simula sa ika-5 palapag.": "Twenty lines in 2:30, starting on floor 5.",
  "Siyam na hanay ng kalat. Linisin, tipid sa piraso.": "Nine rows of rubble. Clear them using as few pieces as you can.",
  "Labinlimang hanay, walang imbak.": "Fifteen lines, no hold.",
  "Dalawang minuto: putik mula sa ilalim, lindol tuwing 30 segundo.": "Two minutes: mud from below, an earthquake every 30 seconds.",
  "Tatlong T-spin bago matapos ang 4 na minuto.": "Three T-spins before 4 minutes are up.",
  "Apat na palapag (40 hanay) sa 5 minuto, simula sa ika-3.": "Four floors (40 lines) in 5 minutes, starting on floor 3.",
  "Nawalan ng kuryente! Flashlight lang ang ilaw. Labindalawang hanay.": "The power's out! Only a flashlight to see by. Twelve lines.",
  "Malakas ang hangin: dumudulas ang piraso. Labinlimang hanay.": "Strong wind: the pieces drift. Fifteen lines.",
  "Mahina ang semento: bawat ikaapat na piraso ay may bitak at guguho. Labinlimang hanay.": "Weak cement: every fourth piece is cracked and will crumble. Fifteen lines.",
  "Lunes: walang dumating na kawayan. Dalawampung hanay nang walang I.": "Monday: the bamboo never came. Twenty lines with no I pieces.",
  "Brownout at hangin nang sabay. Labingwalong hanay.": "A brownout and wind at the same time. Eighteen lines.",
  "Isang martilyo at isang semento lang ang dala mo. Linisin ang kalat.": "You only brought one hammer and one bag of cement. Clear the rubble.",
  "Walang kawayan, at tumataas ang putik. Tumagal nang 90 segundo.": "No bamboo, and the mud is rising. Last 90 seconds.",
  "Bitak na ang lumang pundasyon. Linisin ang pitong hanay ng kalat.": "The old foundation is cracking. Clear seven rows of rubble.",
  "Dalawampu’t limang hanay sa 3 minuto, sa gitna ng malakas na hangin.": "Twenty-five lines in 3 minutes, in a strong wind.",
  "Brownout buong gabi. Kumita ng ₱8,000.": "A brownout all night. Earn ₱8,000.",
  "Tatlumpung hanay habang tumataas ang putik; isang pison lang ang gamit mo.": "Thirty lines while the mud rises; your only tool is one roller.",
  "Walang kawayan, at lumilindol tuwing 25 segundo. Dalawampung hanay.": "No bamboo, and an earthquake every 25 seconds. Twenty lines.",
  "Dalawang minuto: putik mula sa ilalim, at may bitak ang bawat ikalimang piraso.": "Two minutes: mud from below, and every fifth piece is cracked.",
  "Brownout, at anim na hanay ng kalat. Linisin, tipid sa piraso.": "A brownout, and six rows of rubble. Clear them using as few pieces as you can.",
  "Dumating ang City Inspector. Tatlong palapag (30 hanay) bago mapuno ang inspeksyon. Ang bawat REJECTED na malinis mo, may dagdag na oras.": "The City Inspector is here. Three floors (30 lines) before the inspection runs out. Every REJECTED block you clear buys extra time.",
  "{n} hanay": "{n} line{s}",
  "hanay": "lines",
  "piraso": "pieces",
  "tumagal {d}": "last {d}",
  "linisin ang kalat": "clear the rubble",
  "walang imbak": "no hold",
  "{n} imbak lang": "only {n} hold{s}",
  "tumataas ang putik": "rising mud",
  "lindol": "earthquakes",
  "ika-{n} palapag": "start on floor {n}",
  "hangin": "wind",
  "bitak bawat {n}": "cracks every {n}",
  "walang kawayan": "no bamboo",
  "gamit: {g} lang": "tools: {g} only",
  "walang gamit": "no tools",
  "Apat na hanay nang sabay": "Four lines at once",
  "Isang T-spin triple": "One T-spin triple",
  "Tuloy-tuloy": "Nonstop",
  "Malinis": "Spotless",
  "Perfect clear: walang natirang bloke": "Perfect clear: not a block left",
  "Sampung Palapag": "Ten Floors",
  "Umabot sa ika-10 palapag": "Reach floor 10",
  "Pasok sa Oras": "Right on Time",
  "Deadline sa loob ng 2 minuto": "Deadline in under 2 minutes",
  "Matibay sa Bagyo": "Stormproof",
  "Tatlong minuto sa Bagyo": "Three minutes in Storm",
  "Karerista": "Racer",
  "₱20,000 sa isang Karera": "₱20,000 in one Race",
  "Kumpleto sa Gamit": "Fully Equipped",
  "Gumamit ng 10 gamit": "Use 10 tools",
  "Bida sa Barangay": "Barangay Hero",
  "Lahat ng bituin sa isang barangay": "Every star in one barangay",
  "Araw-araw": "Every Day",
  "Naglaro ng Daily": "Played a Daily",
  "Naabot ang pinakamataas na ranggo": "Reached the top rank",
  "Bagyo Week": "Storm Week",
  "Lindol Week": "Quake Week",
  "Gamit Lang": "Tools Only",
  "Mabilis": "Fast",
  "Tumataas ang putik buong linggo. Tatlong minuto, pinakamataas na kita.": "The mud rises all week. Three minutes, highest earnings.",
  "Lumilindol tuwing 20 segundo: dumudulas ang tumpok.": "An earthquake every 20 seconds: the stack slides.",
  "Tools only: bawat ikaapat na piraso, may bagong gamit.": "Tools only: a new tool every fourth piece.",
  "20G: bumabagsak agad ang bawat piraso. Bilis ng isip!": "20G: every piece drops instantly. Think fast!",
  "Lumang patakaran: walang imbak, walang anino, isang susunod lang, walang wall kick.": "Old rules: no hold, no ghost, one next piece, no wall kicks.",
  "Natapos ang Bagyo Week": "Finished Storm Week",
  "Natapos ang Lindol Week": "Finished Quake Week",
  "Natapos ang Gamit Lang": "Finished Tools Only",
  "Natapos ang Mabilis": "Finished Fast",
  "Natapos ang Retro": "Finished Retro",
  "Bloke": "Blocks",
  "Makintab": "Glazed",
  "Neon sa Gabi": "Night Neon",
  "Parol": "Parol Lantern",
  "Pintado": "Painted",
  "Ginto": "Gold",
  "Pang-trabaho": "Work Clothes",
  "Kapote": "Raincoat",
  "Probinsya": "Province",
  "Ang orihinal na materyales.": "The original materials.",
  "Pinakinang na baldosa: may glaze ang bawat bloke.": "Polished tile: every block has a glaze.",
  "Kabibe ng capiz: maputi at kumikinang na parang perlas.": "Capiz shell: white and shimmering like pearl.",
  "Madilim na bloke, maliwanag na gilid. Para sa gabi.": "Dark blocks, bright edges. For the night.",
  "Paskong Pinoy: bawat bloke ay isang ilaw na parol.": "A Filipino Christmas: every block is a glowing parol lantern.",
  "Pinintahang pastel. Para sa may medalyang Malinis.": "Painted in pastels. For holders of the Spotless medal.",
  "Purong ginto. Para lang sa mga Arkitekto.": "Pure gold. For Architects only.",
  "Vest, hard hat at tuwalya.": "Vest, hard hat and towel.",
  "Pormal para sa blessing ng bahay.": "Formal wear for the house blessing.",
  "Pang-liga sa barangay: numero 23.": "For the barangay league: number 23.",
  "Dilaw na kapote para sa bagyo.": "A yellow raincoat for the storm.",
  "Ho ho ho! Simbang gabi na.": "Ho ho ho! It's time for the Christmas dawn masses.",
  "Ang kanto, ang sari-sari store, ang golden hour.": "The street corner, the sari-sari store, the golden hour.",
  "Sa paanan ng mga high-rise: salamin at ilaw ng lungsod.": "At the foot of the high-rises: glass and city lights.",
  "Puting buhangin, dagat at payong sa tabi ng site.": "White sand, the sea and umbrellas beside the site.",
  "Palayan, bundok at bahay-kubo. Para sa mga Kapatas.": "Rice fields, mountains and nipa huts. For Foremen.",
  "Ang butas na may bubong: hindi mo maibabagsak nang diretso ang ladrilyo. Itayo ito (↑ o X), ibaba nang dahan-dahan sa butas, saka iikot papasok bago dumikit.": "A hole with a roof: you can't drop the brick straight in. Stand it up (↑ or X), lower it slowly into the hole, then turn it in before it locks.",
  "Ikot → kaliwa → ↓ hanggang sumayad → ikot ulit → bagsak.": "Turn → left → ↓ until it touches → turn again → drop.",
  "Ganito rin, pero puno ang dalawang hanay. Iikot ang ladrilyo papasok sa ilalim ng bubong: dalawang hanay, apat na putik sa kalaban!": "Same idea, but two lines are full. Turn the brick in under the roof: two lines, and four mud to your rival!",
  "Ang pinakamahirap: tatlong hanay. Ibaba ang ladrilyo nang nakahiga sa tabi ng butas, isingit sa ilalim ng bubong, at iikot pabalik (Z): babagsak ito nang dalawang hanay papasok.": "The hardest: three lines. Bring the brick down lying flat beside the hole, slip it under the roof, and turn it back (Z): it drops two rows in.",
  "Kaliwa ×2 → ↓ hanggang sumayad → kanan → ikot pabalik (Z) → bagsak.": "Left ×2 → ↓ until it touches → right → turn back (Z) → drop.",
  "Apat na luwang sa gitna, may tatlong bloke na sa ilalim. Bawat piraso, isang hanay lang ang buuin: tuloy-tuloy ang clear, lumalaki ang combo. Limang sunod-sunod!": "A four-wide gap in the middle, with three blocks already at the bottom. Complete just one line with each piece: the clears keep coming and the combo grows. Five in a row!",
  "Sundan ang anino: isang hanay bawat piraso, laging tatlong bloke ang natitira.": "Follow the shadow: one line per piece, always three blocks left over.",
  "Ang mahusay na mason, walang sayang na galaw. Ilagay ang bawat piraso sa anino sa pinakakaunting pindot: pindutin at hawakan ang ← o → para dumiretso sa pader.": "A good mason wastes no moves. Put each piece in the shadow with the fewest presses: press and hold ← or → to slide straight to the wall.",
  "Hawakan ang ← o → para sa pader. Ang tamang ikot: isang pindot lang.": "Hold ← or → for the wall. The right turn: just one press.",
  "Bagong peon. Mabagal pero matiyaga: patag at malinis ang salansan.": "A new laborer. Slow but patient: a flat, tidy stack.",
  "Dahan-dahan lang, pare.": "Easy does it, friend.",
  "Sige, turuan mo ako!": "Go on, teach me!",
  "Ayan, may putik ka!": "There, some mud for you!",
  "Uy, tumama!": "Hey, that landed!",
  "Aray, ang bigat!": "Ow, that's heavy!",
  "Teka lang, teka lang!": "Wait, wait!",
  "Ay, susmaryosep!": "Oh, good heavens!",
  "Swerte lang, pare!": "Just lucky, friend!",
  "Ang galing mo, idol!": "You're amazing, idol!",
  "May-ari ng hardware. Kilala niya ang bawat hollow block, at walang butas ang pader niya.": "Owns the hardware store. She knows every hollow block, and her walls have no holes.",
  "Walang utang dito, ha.": "No credit here, okay.",
  "Bayad muna bago laro!": "Pay first, then play!",
  "Libre na yang putik, suki!": "The mud's on the house, regular!",
  "O, dagdag pa!": "Here, have some more!",
  "Hoy, ang daya!": "Hey, no fair!",
  "Naku, puno na ang bodega!": "Oh no, the storeroom's full!",
  "Balik ka bukas, suki!": "Come back tomorrow, regular!",
  "Sige na nga, panalo ka.": "Fine, you win.",
  "Tatlumpung taon sa construction. Iniipon ang kawayan para sa malaking Bayanihan.": "Thirty years in construction. Saves up the bamboo for a big Bayanihan.",
  "Kawayan lang ang kailangan ko.": "Bamboo is all I need.",
  "Tingnan natin, bata.": "Let's see, kid.",
  "BAYANIHAN! Tanggapin mo!": "BAYANIHAN! Take that!",
  "Buhat-buhat yan!": "Heave-ho!",
  "Hindi pa ako tapos!": "I'm not done yet!",
  "Matibay pa rin!": "Still standing strong!",
  "Nasaan na ang kawayan ko?!": "Where's my bamboo?!",
  "Karanasan ang panalo, iho.": "Experience wins, son.",
  "Ikaw na ang bagong mason!": "You're the new mason!",
  "Delivery rider tuwing umaga, kampeon tuwing gabi. Hindi naghihintay ng kawayan.": "Delivery rider by day, champion by night. Never waits for bamboo.",
  "Bilisan mo, may delivery pa ako!": "Hurry up, I've got deliveries!",
  "Go, go, go!": "Go, go, go!",
  "Express delivery ng putik!": "Express mud delivery!",
  "Bilis, oh!": "Fast, huh!",
  "Ang kupad mo pero ang sakit!": "You're slow, but that hurt!",
  "Aguy!": "Ouch!",
  "Traffic! Traffic!": "Traffic! Traffic!",
  "Sa susunod, bilisan mo!": "Next time, be quicker!",
  "Ang bilis mo rin pala!": "You're fast too, huh!",
  "Lisensyadong inhinyero. Mahilig sa diskarte: iniikot ang ladrilyo papasok sa butas.": "A licensed engineer. Loves a clever move: turns the brick into the hole.",
  "Kalkulado ko na ang lahat.": "I've calculated everything.",
  "Physics lang yan.": "It's just physics.",
  "T-spin! Pang-engineer!": "T-spin! Engineer-grade!",
  "Diskarte, hindi swerte.": "Skill, not luck.",
  "Hmm, hindi ko inasahan yan.": "Hmm, I didn't expect that.",
  "Recalculating...": "Recalculating...",
  "Lagpas na sa design load!": "Over the design load!",
  "Q.E.D.": "Q.E.D.",
  "Kailangan kong i-recompute.": "I need to recompute.",
  "Ang Kapatas mismo. Mabilis, matalino, at hindi nagkakamali. Talunin mo siya para sa korona.": "The Foreman himself. Fast, clever and never wrong. Beat him for the crown.",
  "Ipakita mo ang natutunan mo.": "Show me what you've learned.",
  "Walang awa sa site ko.": "No mercy on my site.",
  "Trabaho, hindi laro!": "This is work, not play!",
  "Ganyan magtayo!": "That's how you build!",
  "Overtime ka bukas!": "You're on overtime tomorrow!",
  "Aba, natuto ka na!": "Well now, you've learned!",
  "Magaling, magaling!": "Good, good!",
  "Hindi pa tapos ang shift!": "The shift isn't over!",
  "Balik sa pagsasanay, iho.": "Back to training, son.",
  "Ikaw na ang bagong Kapatas!": "You're the new Foreman!",
  "Bayanihan! Ang galing!": "Bayanihan! Amazing!",
  "Bagong ranggo! Ipagpatuloy mo!": "New rank! Keep it up!",
  "Ingat! Guguho na!": "Careful! It's about to collapse!",
  "Tapos ang trabaho! Galing!": "Job done! Great work!",
  "Gumuho! Bukas ulit tayo.": "It collapsed! We'll try again tomorrow.",
  "RONDA {n}": "ROUND {n}",
  "P1 {a} – {b} P2 · Tatlong ronda": "P1 {a} – {b} P2 · Best of three",
  "LABAN!": "FIGHT!",
  "Lingguhan · tatlong minuto": "Weekly · three minutes",
  "ANG INSPEKTOR": "THE INSPECTOR",
  "Dumating ang City Inspector!": "The City Inspector is here!",
  "Pagsasanay · Sundan ang gintong anino": "Training · Follow the golden shadow",
  "Iisang bilis. Purong laro.": "One speed. Pure play.",
  "40 hanay, bilisan!": "40 lines, hurry!",
  "Tumataas ang baha!": "The flood is rising!",
  "Dalawang minuto. Kita, kita, kita!": "Two minutes. Earn, earn, earn!",
  "Daily {d} · pareho para sa lahat": "Daily {d} · the same for everyone",
  "Ang mga sako sa tabi ng well: putik na paparating. Mag-clear para harangin!": "The sacks beside the well: incoming mud. Clear lines to block it!",
  "Tap: ikot · Drag: galaw · Flick ↓ bagsak, ↑ imbak": "Tap: turn · Drag: move · Flick ↓ drop, ↑ hold",
  "← → galaw · ↑ o X ikot · Z pabalik · ↓ dahan-dahan · Space bagsak · C o Shift imbak · may controller din": "← → move · ↑ or X turn · Z turn back · ↓ soft drop · Space drop · C or Shift hold · controllers work too",
  "+{n} barya": "+{n} coin{s}",
  "{n} pa para sa {r}": "{n} more to {r}",
  "Medalya: {m}": "Medal: {m}",
  "Nakopya! Copied to the clipboard.": "Copied to the clipboard!",
  "Tapos ang kontrata!": "Contract complete!",
  "Hindi natapos…": "Not finished…",
  "Oras na!": "Time's up!",
  "Tapos sa oras!": "Done on time!",
  "Inabot ng baha!": "Caught by the flood!",
  "Gumuho ang pader!": "The wall came down!",
  "Bagong best! New best!": "New best!",
  "Hanay": "Lines",
  "Naitayo": "Built",
  "{n} palapag": "{n} floor{s}",
  "Oras": "Time",
  "Bagong istilo ng bahay: {s}. Piliin sa Tala at Medalya.": "New house style: {s}. Pick it in Stats and medals.",
  "Ang pinakamataas na ranggo sa site!": "The highest rank on the site!",
  "Tabla!": "Draw!",
  "Panalo!": "You win!",
  "Talo…": "You lose…",
  "Tinalo mo si {n}!": "You beat {n}!",
  "Natalo ka ni {n}.": "{n} beat you.",
  "Ipinadala": "Sent",
  "{n} putik": "{n} mud",
  "Natanggap": "Received",
  "Piraso/seg": "Pieces/sec",
  "Susunod: {n}": "Next: {n}",
  "Bagong ranggo!": "New rank!",
  "TABLA!": "DRAW!",
  "P{n} PANALO!": "P{n} WINS!",
  "Panalo si P{n}!": "P{n} wins!",
  "Tapatan · pinakamahusay sa tatlo": "Head to Head · best of three",
  "P1 padala": "P1 sent",
  "P2 padala": "P2 sent",
  "Ronda": "Round",
  "P1 hanay": "P1 lines",
  "P2 hanay": "P2 lines",
  "Ganyan ang tapatan! Kamayan na kayo.": "Now that's a match! Shake hands, you two.",
  "Manlalaro {n}": "Player {n}",
  "Kontrol": "Controls",
  "Padala × · Garbage sent": "Garbage sent ×",
  "Simulang taas · Start height": "Start height",
  "Arrows: galaw at bagsak (↑), , . ikot, / imbak": "Arrows: move and drop (↑), , . turn, / hold",
  "A D galaw, S dahan, W bagsak, Q E ikot, C imbak": "A D move, S soft drop, W drop, Q E turn, C hold",
  "Iisang controller ang dalawang manlalaro. Pumili ng iba.": "Both players are on the same controller. Pick another.",
  "Iisang controller": "Same controller",
  "Pareho ang kontrol ng dalawang manlalaro. Pumili ng ibang kontrol para sa isa sa kanila.": "Both players have the same controls. Pick different controls for one of them.",
  "<b>{u}</b> pindot · pinakakaunti <b>{m}</b>": "<b>{u}</b> presses · fewest <b>{m}</b>",
  "+{n} sayang": "+{n} wasted",
  "walang sayang": "none wasted",
  "kabuuan {n}": "total {n}",
  "PASADO!": "PASSED!",
  "Ayan! Iyan ang T-spin. Ngayon, dalawang hanay naman.": "There! That's a T-spin. Now try it with two lines.",
  "T-spin double: apat na putik sa kalaban. Pang-engineer!": "T-spin double: four mud to your rival. Engineer-grade!",
  "Tatlong hanay sa isang ikot! Handa ka na sa Tatlong T-spin.": "Three lines in one turn! You're ready for Three T-spins.",
  "Tuloy-tuloy! Ganyan ang Sunod-sunod.": "Nonstop! That's how Chain Reaction goes.",
  "Walang sayang na galaw. Tunay na mason!": "Not a wasted move. A true mason!",
  "Subukan na ang kontrata: {c}.": "Now try the contract: {c}.",
  "ULIT!": "AGAIN!",
  "May sayang na pindot o maling puwesto": "A wasted press or the wrong spot",
  "Naputol ang combo": "The combo broke",
  "Hindi T-spin: iikot bago dumikit": "Not a T-spin: turn it before it locks",
  "+{n} PUTIK": "+{n} MUD",
  "HARANG {n}": "BLOCKED {n}",
  "PANALO!": "YOU WIN!",
  "Gumuho ang kay {n}": "{n}'s wall came down",
  "AUTO: si Kapatas-bot muna ang maglalaro. 1 · 2 · 3 para sa bilis (1×, 3×, 10×); ang code ulit para bumalik.": "AUTO: Kapatas-bot is playing. 1 · 2 · 3 for speed (1×, 3×, 10×); the code again to take back control.",
  "Ikaw na ulit ang naglalaro.": "You're playing again.",
  "ranggong <b>{r}</b>": "the <b>{r}</b> rank",
  "kulang pa ng {n} XP": "{n} XP to go",
  "Sarado pa": "Not open yet",
  "Tapusin muna ang <b>{p}</b> (kahit 1 ★) para mabuksan ang <b>{c}</b>.": "Finish <b>{p}</b> first (even 1 ★) to open <b>{c}</b>.",
  "Buksan ang {p}": "Open {p}",
  "Kailangan ng <b>{need} ★</b> sa Brgy. {b}. Mayroon kang {have} ★, kulang pa ng <b>{short} ★</b>.": "You need <b>{need} ★</b> in Brgy. {b}. You have {have} ★, so <b>{short} ★</b> to go.",
  "Sarado pa ang Kabanata 2": "Chapter 2 isn't open yet",
  "Bubukas ito kapag natapos ang <b>{c}</b>, o may <b>30 ★</b> ka sa Kabanata 1. Mayroon kang {have} ★.": "It opens when you finish <b>{c}</b>, or have <b>30 ★</b> in Chapter 1. You have {have} ★.",
  "ISANG HANAY": "ONE LINE",
  "Sunod-sunod! ×1.5": "Back-to-back! ×1.5",
  "Tulong-tulong!": "All together!",
  "DALAWA!": "DOUBLE!",
  "TATLO!": "TRIPLE!",
  "SUNOD-SUNOD ×1.5": "BACK-TO-BACK ×1.5",
  "TULOY-TULOY ×{n}": "COMBO ×{n}",
  "Tip: apat na hanay nang sabay ay BAYANIHAN, ang pinakamalaking kita!": "Tip: four lines at once is a BAYANIHAN, the biggest earner!",
  "Palapag {n}!": "Floor {n}!",
  "Bagong palapag · New floor": "New floor",
  "Tumataas ang baha mula sa ilalim! Punuin ang butas para matanggal ang putik.": "The flood is rising from below! Fill the gaps to clear the mud.",
  "Bagong gamit: {t}! Pindutin ang kahon.": "New tool: {t}! Tap the box.",
  "May bagong gamit: {t}! Pindutin ang E para gamitin.": "New tool: {t}! Press E to use it.",
  "LINDOL!": "EARTHQUAKE!",
  "MALINIS!": "SPOTLESS!",
  "PASADO +{n}s": "PASSED +{n}s",
  "HANGIN →": "WIND →",
  "← HANGIN": "← WIND",
  "Hangin: dumudulas ang piraso sa direksyon ng hangin. Bantayan ang palaso!": "Wind: the piece drifts the way the wind blows. Watch the arrow!",
  "MAY ILAW NA!": "LIGHTS ON!",
  "Brownout! Ang flashlight lang ang ilaw: sundan ang piraso.": "Brownout! Only the flashlight shines: follow the piece.",
  "May bitak ang piraso: guguho ito pagkatapos ng ilang piraso.": "This piece is cracked: it crumbles after a few more pieces.",
  "Sinalo ng andamyo ang pader!": "The scaffold caught the wall!",
  "Sinalo ang putik": "Caught the mud",
  "TAPOS!": "DONE!",
  "{n} kontrata sa {b} barangay, may City Inspector.": "{n} contracts across {b} barangays, with a City Inspector.",
  "Wala pang best": "No best yet",
  "Ngayon {s}": "Today {s}",
  "Liga {a}/{b} · {w} panalo": "League {a}/{b} · {w} wins",
  "{a}/{b} pasado": "{a}/{b} passed",
  "2 manlalaro": "2 players",
  "<b>{n}</b> araw": "<b>{n}</b> day{s}",
  "Madali: mas mabagal ang bagsak at mas matagal bago dumikit.": "Easy: slower falling, and more time before a piece locks.",
  "Katamtaman: ang klasiko.": "Medium: the classic.",
  "Mahirap: magsisimula sa ika-6 na palapag.": "Hard: you start on floor 6.",
  "(Bahay, Klasiko, Deadline, Bagyo, Karera)": "(House, Classic, Deadline, Storm, Race)",
  "NGAYONG LINGGO": "THIS WEEK",
  "Walang katapusan. Bawat 10 hanay, bagong palapag. May gamit.": "Endless. Every 10 lines, a new floor. With tools.",
  "Purong laro: iisang bilis buong laro, walang gamit, walang eksena.": "Pure play: one speed all game, no tools, no cutscenes.",
  "40 hanay sa tanghaling tapat. Pinakamabilis ang panalo.": "40 lines in the noonday sun. Fastest wins.",
  "Tumataas ang putik mula sa ilalim. Tumagal hangga’t kaya.": "Mud rises from below. Last as long as you can.",
  "Dalawang minuto, pinakamataas na kita. May gamit.": "Two minutes, highest earnings. With tools.",
  "Parehong piraso para sa lahat ngayong araw. Dalawang minuto.": "The same pieces for everyone today. Two minutes.",
  "Ang twist ngayong linggo. Medalya at token.": "This week's twist. Medals and tokens.",
  "Ang well mo laban sa kalaban. Magpadala ng putik.": "Your well against a rival's. Send them mud.",
  "Dalawang tao, isang keyboard. Pinakamahusay sa tatlo.": "Two people, one keyboard. Best of three.",
  "Mga aralin ni Kapatas: T-spin, combo, finesse.": "Kapatas's lessons: T-spins, combos, finesse.",
  "0 · agad": "0 · instant",
  "Wika · Language": "Language",
  "Laro · Game": "Game",
  "Anino ng piraso · Ghost piece": "Ghost piece",
  "Oo · On": "On",
  "Wala · Off": "Off",
  "Eksena sa Bayanihan at bagong palapag · Cutscenes": "Cutscenes",
  "Buo · Full": "Full",
  "Mga alok na may patalastas · Reward ads": "Reward ads",
  "Anggulo · Angle": "Angle",
  "Pahilig · Angled": "Angled",
  "Tuwid · Straight": "Straight",
  "Yanig ng camera · Camera shake": "Camera shake",
  "Kalmado · Reduced": "Reduced",
  "Tunog at itsura · Sound and look": "Sound and look",
  "Musika · Music": "Music",
  "Tunog · Effects": "Effects",
  "Boses · Voice": "Voice",
  "Boses ni Kapatas · Voice": "Kapatas's voice",
  "Yanig · Haptics (phone, controller)": "Haptics (phone, controller)",
  "Mataas": "High",
  "Mababa": "Low",
  "Kontrol · Controls": "Controls",
  "Susunod na piraso · Next queue": "Next queue",
  "Bilis ng dahan · Soft drop": "Soft drop speed",
  "Agad": "Instant",
  "Ikot 180° · Half turn": "Half turn (180°)",
  "Imbak · Hold": "Hold",
  "Finesse coach (sa lahat ng mode)": "Finesse coach (in every mode)",
  "Habulin ang multo · Ghost race": "Ghost race",
  "Sa susunod na laro ang bago. Applies next game.": "Changes apply next game.",
  "Mga pindutan · Remap": "Remap",
  "Kailangan ng 8 ★ sa isang barangay para sa susunod.": "You need 8 ★ in a barangay to open the next.",
  "Kabanata 2: tapusin ang Ang Huling Bahay, o 30 ★.": "Chapter 2: finish The Last House, or earn 30 ★.",
  "Kontrata {n}/5": "Contract {n}/5",
  "Walang dagdag na pahirap.": "No extra twist.",
  "Aralin: {n}": "Lesson: {n}",
  "May dala kang {t}! Pindutin ang E (o ang button) para gamitin.": "You brought a {t}! Press E (or the button) to use it.",
  "{a}/{b} natalo · {w} panalo lahat": "{a}/{b} beaten · {w} wins in all",
  "Hindi pa puwede": "Not yet",
  "Talunin muna si <b>{p}</b> sa Liga bago si <b>{r}</b>.": "Beat <b>{p}</b> in the League before <b>{r}</b>.",
  "Labanan si {p}": "Fight {p}",
  "Bagong peon: mabagal at madalas magkamali. Para sa unang laban.": "A new laborer: slow and makes mistakes. For your first match.",
  "Sanay na mason: nag-iipon ng kawayan para sa Bayanihan.": "A practiced mason: saves bamboo for Bayanihans.",
  "Si Kapatas mismo: mabilis, may T-spin, halos walang mali.": "Kapatas himself: fast, does T-spins, almost never wrong.",
  "Para sa {c}": "For {c}",
  "Para sa lahat": "For everyone",
  "Aralin {a}/{b}": "Lesson {a}/{b}",
  "Pasado na": "Passed",
  "Kailangan sa kontrata: {c}.": "Needed for the contract: {c}.",
  "Ang gintong anino ang tamang puwesto; ipapakita ng coach ang sayang na pindot.": "The golden shadow is the right spot; the coach shows any wasted presses.",
  "Huling laro · Last game": "Last game",
  "Panoorin": "Watch",
  "Wala pang replay. Maglaro ng Deadline, Karera o Daily: ang pinakamagandang takbo mo ay itatabi rito.": "No replays yet. Play Deadline, Race or the Daily: your best runs are kept here.",
  "Nakopya ang link! Replay link copied.": "Replay link copied!",
  "Sira ang replay link · This replay link is broken.": "This replay link is broken.",
  "wala": "none",
  "Pindutin…": "Press…",
  "+ Dagdag": "+ Add",
  "Palitan": "Change",
  "Pumili ng aksyon, saka pindutin ang bagong key o button. Esc para kanselahin.": "Pick an action, then press the new key or button. Esc to cancel.",
  "Ang <b>{k}</b> ay gamit na ng <b>{who}</b>. Ilipat dito sa {act}?": "<b>{k}</b> is already used by <b>{who}</b>. Move it to {act}?",
  "Ilipat · Move": "Move",
  "Huwag · Cancel": "Cancel",
  "Isahan · Solo": "Solo",
  "Tapatan · P1": "Head to Head · P1",
  "Tapatan · P2": "Head to Head · P2",
  "Ang d-pad at kaliwang stick: galaw at dahan.": "The d-pad and left stick: move and soft drop.",
  "Pindutin ang key para sa <b>{act}</b>… (Esc: kanselahin)": "Press a key for <b>{act}</b>… (Esc: cancel)",
  "Pindutin ang button sa controller para sa <b>{act}</b>… (Esc: kanselahin)": "Press a controller button for <b>{act}</b>… (Esc: cancel)",
  "Ibinalik sa default · Controls reset": "Controls reset",
  "Kaliwa · Left": "Left",
  "Kanan · Right": "Right",
  "Dahan · Soft drop": "Soft drop",
  "Bagsak · Hard drop": "Hard drop",
  "Ikot · Turn": "Turn",
  "Pabalik · Turn back": "Turn back",
  "Ikot 180°": "Turn 180°",
  "Gamit · Tool": "Tool",
  "Hinto · Pause": "Pause",
  "Susunod: {n} sa": "Next: {n} in",
  "Inspektor": "Inspector",
  "Libre": "Free",
  "Suot": "Wearing",
  "Iyo na": "Owned",
  "Suot na": "Wearing it",
  "Isuot · Equip": "Equip",
  "Bilhin": "Buy",
  "Isuot · Trial": "Wear (trial)",
  "Subukan nang 24 oras": "Try it for 24 hours",
  "Trial · {t} pa": "Trial · {t} left",
  "Kulang pa ang ipon.": "Not enough saved yet.",
  "Bukas kapag nakuha ang {x}.": "Opens when you get {x}.",
  "medalyang {m}": "the {m} medal",
  "ranggong {r}": "the {r} rank",
  "Suot mo ang {n} nang 24 oras!": "You're wearing {n} for 24 hours!",
  "Naka-lock pa": "Still locked",
  "Hindi ito nabibili: bubukas ang <b>{n}</b> kapag nakuha mo ang {x}.": "Not for sale: <b>{n}</b> opens when you get {x}.",
  "medalyang <b>{m}</b> ({d})": "the <b>{m}</b> medal ({d})",
  "{n} barya": "{n} coin{s}",
  "{n} token": "{n} token{s}",
  "at": "and",
  "Kulang ang barya": "Not enough coins",
  "Kulang ang token": "Not enough tokens",
  "Ang <b>{n}</b> ay {p}. Mayroon kang {c} at {t}, kulang pa ng {s}.": "<b>{n}</b> costs {p}. You have {c} and {t}, so you need {s} more.",
  "+{n} barya · patalastas": "+{n} coins · ad",
  "Nabili: {n}!": "Bought: {n}!",
  "Medalya": "Medal",
  "{h} bahay · {f} palapag lahat": "{h} houses · {f} floors in all",
  "Wala pang natapos na bahay. Sa Bahay, bawat limang palapag ay isang buong bahay: may larawan ito rito.": "No finished houses yet. In House mode, every five floors makes a whole house, and its picture goes here.",
  "Natapos {d}": "Finished {d}",
  "Palapag": "Floors",
  "{n} PALAPAG": "{n} FLOOR{S}",
  "Natapos ko ang {s}: {n} palapag!": "I finished a {s}: {n} floors!",
  "Naka-save ang larawan · Image saved": "Image saved",
  "Nailigtas ng palugit ang streak mo!": "A grace day saved your streak!",
  "Araw {n} ng streak: +{xp} XP, +{c} barya": "Day {n} of your streak: +{xp} XP, +{c} coins",
  "Walang gantimpala: hindi tinapos ang patalastas.": "No reward: the ad wasn't finished.",
  "Doblehin: +{n} barya": "Double it: +{n} coins",
  "+{n} barya! Doble ang kita.": "+{n} coins! Double the earnings.",
  "+{n} barya ({left} pa ngayon)": "+{n} coins ({left} left today)",
  "Overtime: <b>2×</b> XP · {n} laro pa": "Overtime: <b>2×</b> XP · {n} game{s} left",
  "Overtime: 2× XP sa {n} laro": "Overtime: 2× XP for {n} game{s}",
  "+{n} barya!": "+{n} coins!",
  "Overtime! Doble ang XP sa susunod na {n} laro.": "Overtime! Double XP for the next {n} game{s}.",
  "Iligtas ang {n}-araw na streak": "Save your {n}-day streak",
  "Naligtas! Araw {n} ng streak mo.": "Saved! Day {n} of your streak.",
  "Doblehin ang barya": "Double the coins",
  "Gamit sa simula": "A tool to start with",
  "Iligtas ang streak": "Save the streak",
  "Mag-login para sa Ranking": "Log in for the Ranking",
  "Ipinapadala sa Ranking…": "Sending to the Ranking…",
  "Hindi maipadala ang replay dito.": "Can't send the replay from here.",
  "Walang koneksyon: ipapadala kapag may internet na.": "No connection: it'll be sent when you're back online.",
  "#{r} sa {b} (sa {of})": "#{r} in {b} (of {of})",
  "bagong best sa Ranking!": "new best in the Ranking!",
  "best mo: {v}": "your best: {v}",
  "Naipadala ang laro: #{r} sa {b}": "Game sent: #{r} in {b}",
  "bagong best!": "new best!",
  "Naka-login bilang": "Logged in as",
  "Nasa server ang XP, ranggo, barya, medalya, bituin at mga nabili mo, at ang puwesto mo sa Ranking. Kahit burahin ang browser data o lumipat ng device, mag-login lang ulit.": "Your XP, rank, coins, medals, stars and purchases, and your place in the Ranking, are kept on the server. Even if you clear your browser data or switch devices, just log in again.",
  "I-sync ngayon": "Sync now",
  "Mag-logout": "Log out",
  "Sini-sync…": "Syncing…",
  "Naka-save sa server · Saved": "Saved to the server",
  "Naka-logout. Nasa device pa rin ang progreso mo.": "Logged out. Your progress is still on this device.",
  "Mag-login": "Log in",
  "Gumawa ng account": "Create an account",
  "Pangalan": "Name",
  "3–16: letra, numero, _ . -": "3–16: letters, numbers, _ . -",
  "8 o higit pa; huwag ang pangalan o 12345678": "8 or more; not your name or 12345678",
  "Gumawa at mag-login": "Create and log in",
  "Ang progreso mo sa device na ito ay dadalhin sa bagong account. <b>Walang email:</b> tandaan ang password mo.": "Your progress on this device moves to the new account. <b>There's no email:</b> remember your password.",
  "Mag-login para maibalik ang progreso mo at makasali sa Ranking, kahit na-clear ang browser.": "Log in to get your progress back and join the Ranking, even after clearing your browser.",
  "Sinusuri na hindi ka bot…": "Checking you're not a bot…",
  "Kinukuha…": "Loading…",
  "Panoorin ang laro ni {n}": "Watch {n}'s game",
  "Wala pang nakapasok dito. Ikaw na ang mauna!": "Nobody's on this board yet. Be the first!",
  "Ikaw: <b>#{r}</b> sa {n}": "You: <b>#{r}</b> of {n}",
  "Wala ka pa rito, {n}. Maglaro ng {m}!": "You're not on here yet, {n}. Play {m}!",
  "Hindi naipadala.": "Couldn't send it.",
  "Hindi na-sync.": "Couldn't sync.",
  "Hindi nakapasok.": "Couldn't log in.",
  "Walang replay.": "No replay.",
  "Hindi makuha ang Ranking.": "Couldn't load the Ranking.",
  "Walang koneksyon. Subukan ulit.": "No connection. Try again.",
  "Laro": "Games",
  "Gamit na nagamit": "Tools used",
  "Oras sa site": "Time on site",
  "Bituin sa Proyekto": "Project stars",
  "MEDALYA": "MEDALS",
  "GAMIT SA RANGGO": "RANK TOOLS",
  "ISTILO NG BAHAY": "HOUSE STYLE",
  "Bubukas ang <b>{s}</b> sa {r}.": "<b>{s}</b> opens at {r}.",
  "Ronda {n}": "Round {n}",
  "{n} paparating": "{n} incoming",
  "{a}/{b} piraso": "{a}/{b} pieces",
  "iikot papasok": "turn it in",
  "Sayang": "Wasted",
  "{n} hanay pa": "{n} line{s} to go",
  "{n} hanay · bilis {s}": "{n} lines · speed {s}",
  "Palapag {f} · {n} hanay": "Floor {f} · {n} lines",
  "baha {s}s": "flood {s}s",
  "Natitira": "Left",
  "{a}/{b} hanay": "{a}/{b} lines",
  "{t} pa": "{t} left",
  "{n} kalat": "{n} rubble",
  "Tapos ang replay · Pindutin ang play para ulitin": "Replay over · Press play to watch again",
  "BAHAY NA!": "IT'S A HOUSE!",
  "{n} palapag · Salamat, bayanihan!": "{n} floor{s} · Thank you, everyone!",
  "Naibalik ang progreso ni {n} · Progress restored": "{n}'s progress restored",
  "KITA": "EARNINGS",
  "ORAS": "TIME",
  "TALA": "STATS",
  "SUSUNOD": "NEXT",
  "KALABAN": "RIVAL",
  "Tuloy-tuloy ×{n}": "Combo ×{n}",
  "Isang hanay!": "One line!",
  "Dalawa!": "Double!",
  "Tatlo!": "Triple!",
  "TAPOS! Deadline met!": "DONE! Deadline met!",
  "Baha": "Flood",
  "Ang Bayanihan, apat na hanay nang sabay, ang pinakamalaking kita.": "The Bayanihan, four lines at once, earns the most.",
  "Itabi ang kawayan sa IMBAK para sa Bayanihan.": "Keep the bamboo in HOLD for a Bayanihan.",
  "Tingnan ang anino sa ibaba para alam mo kung saan babagsak.": "Watch the ghost below so you know where the piece will land.",
  "Huwag mag-iwan ng butas sa ilalim: mahirap nang punan.": "Don't leave holes underneath: they're hard to fill later.",
  "T-spin: iikot ang ladrilyo papasok sa butas para sa dagdag na kita.": "T-spin: turn the brick into a hole for extra earnings.",
  "Sunod-sunod na clear, may dagdag na bonus. Tuloy-tuloy lang!": "Clears in a row earn a bonus. Keep it going!",
  "Sa Bagyo, maglinis agad bago umapaw ang baha.": "In Storm, clear fast before the flood spills over.",
  "Sa totoong construction site, laging naka-hard hat at safety shoes.": "On a real construction site, it's always hard hat and safety shoes.",
  "Pahinga rin pag pagod na ang mata, ha. Uminom ng tubig!": "Rest when your eyes get tired, okay? Drink some water!",
  "Tara, trabaho na!": "Let's get to work!",
  "Buhos na tayo!": "Time to pour!",
  "Simulan na natin!": "Let's begin!",
  "Ayos!": "Nice!",
  "Sige lang!": "Keep going!",
  "Isa pa!": "One more!",
  "BAYANIHAN! Galing!": "BAYANIHAN! Brilliant!",
  "Ganyan ang tulungan!": "That's teamwork!",
  "Buhat-buhat!": "Heave-ho!",
  "Galing ng diskarte!": "Clever move!",
  "Ikot-pasok! Ang husay!": "Spun right in! Skillful!",
  "Parang engineer ka, ah!": "You're like an engineer!",
  "Tuloy-tuloy!": "Nonstop!",
  "Wag tumigil!": "Don't stop!",
  "Bagong palapag!": "New floor!",
  "Taas pa!": "Higher!",
  "Ingat! Ang taas na!": "Careful! It's getting high!",
  "Babagsak yan!": "That's going to fall!",
  "Linisin muna!": "Clear it first!",
  "Bilisan, bagyo!": "Hurry, the storm!",
  "Gumuho! Overtime tayo bukas.": "It collapsed! Overtime tomorrow.",
  "Ay, sayang ang semento!": "Oh, what a waste of cement!",
  "Tapos sa oras! Libre kita ng merienda!": "Done on time! Snacks are on me!",
  "Pasok sa deadline!": "Made the deadline!",
  "Sunod-sunod! Ang galing!": "Back-to-back! Brilliant!",
  "Isa pang ganyan!": "Another one like that!",
  "Walang tigil, ha!": "No stopping you!",
  "Konti na lang, guguho na!": "Just a bit more and it falls!",
  "Delikado! Ibaba mo na!": "Dangerous! Bring it down!",
  "Susmaryosep, ang taas!": "Good heavens, it's so high!",
  "Nasaan na ang kawayan?!": "Where's the bamboo?!",
  "Wala pang kawayan. Diskarte muna!": "No bamboo yet. Get creative!",
  "Matagal pa ang kawayan, ha.": "The bamboo's taking a while.",
  "Ayan na ang kawayan!": "Here comes the bamboo!",
  "Sa wakas, kawayan!": "Bamboo, at last!",
  "Gamitin mo yan!": "Use that!",
  "Ayos ang gamit!": "Good tool!",
  "Diskarte ng tunay na mason!": "A true mason's move!",
  "Lindol! Kapit!": "Earthquake! Hold on!",
  "Yumayanig! Ingat!": "It's shaking! Careful!",
  "Tapos ang bahay! Salamat sa lahat!": "The house is done! Thanks, everyone!",
  "Bahay na! Kain tayo mamaya!": "It's a house! Let's eat later!",
  "Ulitin natin. Kaya mo yan!": "Let's go again. You can do it!",
  "Sige, isa pa!": "Come on, one more!",
  "Dahan-dahan lang. Ulit!": "Take it slow. Again!",
  "Tara, laban!": "Come on, let's fight!",
  "Handa ka na ba?": "Are you ready?",
  "Ayan ang putik mo!": "There's your mud!",
  "Tanggapin mo yan!": "Take that!",
  "Aray!": "Ouch!",
  "Ang galing mo, ah!": "You're good, huh!",
  "Patay, ang taas na!": "Uh-oh, it's getting high!",
  "Sa susunod na lang!": "Next time, then!",
  "Ang galing mo!": "You're great!",
  "Inspeksyon! Tingnan natin ang trabaho mo.": "Inspection! Let's see your work.",
  "Nasaan ang building permit?": "Where's the building permit?",
  "REJECTED!": "REJECTED!",
  "Hindi pasado ito!": "This doesn't pass!",
  "Ayusin mo yan!": "Fix that!",
  "Ito, mali!": "This one's wrong!",
  "Hmm. Pwede na.": "Hmm. Acceptable.",
  "Sige, pasado yan.": "Fine, that passes.",
  "Malapit na ang deadline ng inspeksyon!": "The inspection deadline is close!",
  "Tik-tak, tik-tak...": "Tick-tock, tick-tock...",
  "Pasado! Aprubado ang bahay.": "Passed! The house is approved.",
  "Maganda ang trabaho. Pirmado na.": "Good work. It's signed.",
  "Ipapasara ko ang site na ito!": "I'm shutting this site down!",
  "Bagsak ang inspeksyon!": "Inspection failed!",
  // 3D words and the weekly button
  "Laruin": "Play",
  "HANGIN · SA KANAN": "WIND · TO THE RIGHT",
  "HANGIN · SA KALIWA": "WIND · TO THE LEFT",
  "SINALO NG ANDAMYO!": "THE SCAFFOLD HELD!",
  "ANDAMYO!": "SCAFFOLD!",
  "MARTILYO!": "HAMMER!",
  "SEMENTO!": "CEMENT!",
  "KREYN!": "CRANE!",
  "PISON!": "ROLLER!",
  "MERIENDA!": "SNACK!",
  "PLUMADA!": "PLUMB LINE!",
  "BARENA!": "DRILL!",
  // the server's answers (api/_hb.mjs), shown as they come
  "Hindi kilalang hirap.": "Unknown difficulty.",
  "Hindi kilalang tanong.": "Unknown request.",
  "Hindi mapatakbo ang replay.": "The replay couldn't be played.",
  "Hindi naka-login.": "Not logged in.",
  "Hindi natapos ang 40 hanay.": "The 40 lines weren't finished.",
  "Hindi pa tapos ang laro.": "The game isn't over yet.",
  "Hindi pumasa ang pagsusuri. I-refresh at subukan ulit.": "The check didn't pass. Refresh and try again.",
  "Hindi tugma ang laro.": "The game doesn't match.",
  "Kopya ito ng laro ng iba.": "This is a copy of someone else's game.",
  "Lampas sa bilis ng tao ang larong ito.": "This game is faster than a person can play.",
  "Lumang Daily na ito.": "This is an old Daily.",
  "Lumang lingguhan na ito.": "This is an old Weekly.",
  "Mali ang pangalan o password.": "Wrong name or password.",
  "Masyadong madaling hulaan ang password na iyan.": "That password is too easy to guess.",
  "Masyadong mahaba ang replay.": "The replay is too long.",
  "Masyadong malaki ang save.": "The save is too big.",
  "May gumagamit na ng pangalang iyan.": "That name is taken.",
  "Mukhang bot ang naglaro nito: masyadong pantay ang pindot.": "This looks like a bot played it: the presses are too even.",
  "Pangalan: 3 hanggang 16 na letra, numero, _ . o -": "Name: 3 to 16 letters, numbers, _ . or -",
  "Password: 8 hanggang 72 na karakter.": "Password: 8 to 72 characters.",
  "Sira ang replay.": "The replay is broken.",
  "Walang ganyan.": "No such thing.",
  "Walang ganyang replay.": "No such replay.",
  "Walang ganyang talaan.": "No such board.",
  "Walang kita.": "No earnings.",
  "Walang laman ang save.": "The save is empty.",
  "Walang talaan ang larong ito.": "This game has no board.",
  "Masyadong marami. Subukan mamaya.": "Too many requests. Try again later.",
  "Masyadong maraming subok. Maghintay muna.": "Too many tries. Please wait a moment.",
  "{d}a {h}o": "{d}d {h}h",
  "{h}o {m}m": "{h}h {m}m",
};
